version: '3.8'
services:
  auth-service:
    image: bangjinseong/auth-service:latest
    container_name: auth-container
    restart: unless-stopped
    build: .
    ports:
      - "8200:8200"
    depends_on:
      - database
    environment:
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - auth-network


  database:
    image: mysql:8.0.33
    container_name: auth_db_container
    restart: unless-stopped
    ports:
      - "3200:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - auth-network

networks:
  auth-network:
